@Server_HostAddress = http://localhost:5102/rest

GET {{Server_HostAddress}}?PageSize=3
Accept: application/json

###

GET {{Server_HostAddress}}/1
Accept: application/json

###
POST {{Server_HostAddress}}
Content-Type: application/json

{
  "ProductName": "Товар 123",
  "Quantity": 12.3
}
